#!/bin/sh

VAR=" system update and upgrade hasbeen completed"
VAR1=" system autoremove and autoclean hasbeen completed"

#For this to system update and upgrade.
sudo apt-get update && sudo apt-get upgrade -y
echo ${VAR}

#For this is to remove system cached data.
sudo apt-get autoremove && sudo apt-get autoclean -y
echo ${VAR1}

echo "Last run" > script_log.txt
echo $(date "+%Y-%m-%d-%H-%M-%S") > script_log.txt

now="$(date)"
printf "$now"
exit
